apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

labels:
  - pairs:
      app.kubernetes.io/name: kafka-topic-controller

resources:
  - crd.yaml
  - sa.yaml
  - rbac-role.yaml
  - rbac-role-binding.yaml
  - deployment.yaml
