apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-topic-controller-manager-role
rules:
- apiGroups:
  - kafka.kanggara.my.id
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.kanggara.my.id
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
