apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-topic-controller-role
rules:
- apiGroups:
  - kafka.kanggara.my.id
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kafka.kanggara.my.id
  resources:
  - kafkatopics/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kafka.kanggara.my.id
  resources:
  - kafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
